import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for Docusaurus.
 *
 * Here we create a primary sidebar that includes:
 * - An autogenerated section for all standard docs.
 * - A dedicated "API Reference" category which automatically generates a sidebar
 *   from the contents of the `api` subfolder.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates sidebar items from all docs in the docs folder.
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api', // Generates API docs sidebar from the docs/api folder.
        },
      ],
    },
  ],
};

export default sidebars;
